version: "3.9"
services:
  web:
      build: .
      ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
      depends_on:
      - postgres
      - rabbitmq
      - redis
      networks:
      - myapp
      env_file:
      - .env
  postgres:
    image: postgres:latest
    environment:
      - DB_URL=postgresql://postgres:password@localhost:${HOST_PORT_POSTGRES}/nodejs-db
    ports:
      - "${HOST_PORT_POSTGRES}:${CONTAINER_PORT_POSTGRES}"
    networks:
      - myapp
    env_file:
      - .env
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - BUS_URL=amqp://user:pass@localhost:${HOST_PORT_RABBITMQ}
    ports:
      - "${HOST_PORT_RABBITMQ}:${CONTAINER_PORT_RABBITMQ}"
    networks:
      - myapp
    env_file:
      - .env
  redis:
    image: redis:latest
    environment:
      - CACHE_URL=redis://localhost:${HOST_PORT_REDIS}
    ports:
      - "${HOST_PORT_REDIS}:${CONTAINER_PORT_REDIS}"
    networks:
      - myapp
    env_file:
      - .env


networks:
  myapp: